#!/bin/bash

set -e

p=.
standard=PHPCompatibility

params=()

volumes=()

usage() {
    echo "Usage: "
    echo "$0"' [-v|--volume list] [-p .]|<-p path/to/php/files> [--standard PHPCompatibility[,...]] [--version ver_min[-[ver_max]]] [PHP CodeSniffer options]'
    echo "$0 --usage"
    cat <<EOF

docker options:
    -v, --volume list      Bind mount a volume

phpcs options:
    -p path             => docker: -v path:/www; phpcs -p /www
    --standard names    => phpcs --standard=names
    --version vers      => phpcs --runtime-set testVersion "vers"
    -h|--help           => phpcs --help

--usage                 Print this message

EOF
}

while [ $# -gt 0 ]; do
    case $1 in
    -p)
        shift
        [ -n "$1" ] && [ -d "$1" ] && p="$1"
        ;;
    --standard)
        shift
        [ -n "$1" ] && standard="$1"
        ;;
    --usage)
        usage
        exit 1
        ;;
    --ver|--version)
        shift
        [ -n "$1" ] && params=("${params[@]}" --runtime-set testVersion "$1")
        ;;
    -v|--volume)
        shift
        [ -n "$1" ] && volumes=("${volumes[@]}" -v "$1")
        ;;
    *)
        params=("${params[@]}" "$1")
        ;;
    esac
    shift
done

set -x
docker run --rm -it -v "$p"/:/www "${volumes[@]}" moremay/php-compatibility:latest phpcs -p /www --extensions=php --standard="$standard" "${params[@]}"
