#!/bin/sh -e

cd /
docker-php-source delete

dir="$1"
[ -n "$dir" ] || dir="/usr/local"

runDeps="$(
    scanelf --needed --nobanner --format '%n#p' --recursive $dir |
        tr ',' '\n' |
        sort -u |
        awk 'system("[ -e '$dir'/lib/" $1 " ]") == 0 { next } { print "so:" $1 }'
)"
apk add --no-cache $runDeps

apk del --no-network .phpize-deps

echo "dependencies:"
echo "$runDeps"
