#!/bin/sh -e

cd /
docker-php-source delete

apt-mark auto '.*' >/dev/null

savedAptMark="$(cat /tmp/.apt-mark 2>/dev/null)"
[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark

dir="$1"
[ -n "$dir" ] || dir="/usr/local"

find "$dir" -type f -executable -exec ldd '{}' ';' |
    awk '/=>/ { print $(NF-1) }' |
    sort -u |
    xargs -r dpkg-query --search |
    cut -d: -f1 |
    sort -u |
    xargs -r apt-mark manual

apt-mark showmanual | tee /tmp/.apt-mark

apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false
