name: Build PHP 5.4

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "5.4/Dockerfile"

jobs:
  build:
    if: vars.ENABLED != ''
    runs-on: ubuntu-latest
    container:
      image: gitea/runner-images:ubuntu-latest
      volumes:
        - /mnt/workflows/docker-php:/mnt/workflows/docker-php
    defaults:
      run:
        working-directory: /mnt/workflows/docker-php
    steps:
      - name: Build and Test PHP 5.4
        id: build
        run: ./build.sh 5.4 -t

      - name: Docker login
        if: success() && vars.ENABLED_PUSH != ''
        run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin

      - name: Push PHP 5.4
        if: success() && vars.ENABLED_PUSH != ''
        run: ./build.sh 5.4 -p
