name: Build PHP 8.5

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "8.5/Dockerfile"

jobs:
  build:
    if: ${{ vars.ENABLED == 'yes' }}
    runs-on: ubuntu-latest
    container:
      image: gitea/runner-images:ubuntu-latest
      volumes:
        - /mnt/workflows/docker-php:/mnt/workflows/docker-php
    defaults:
      run:
        working-directory: /mnt/workflows/docker-php
    steps:
      - name: Build and Test PHP 8.5
        id: build
        run: ./build.sh 8.5 -t

      - name: Docker login
        if: success() && vars.ENABLED_PUSH == 'yes'
        run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin

      - name: Push PHP 8.5
        if: success() && vars.ENABLED_PUSH == 'yes'
        run: ./build.sh 8.5 -p

      - name: Push PHPCS
        if: success() && vars.ENABLED_PUSH == 'yes'
        run: ./build.sh phpcs -t -p
