name: "CI: 7.4"

on:
  push:
    paths:
      - "7.4/*"

jobs:
  build_74:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./7.4
        file: ./7.4/Dockerfile
        push: true
        tags: |
          moremay/php:7.4
          moremay/php:7.4-alpine

    - name: Build composer
      shell: bash
      run: |
        ./build.sh 7.4 --composer -p
