name: "CI: cmpt"

on:
  push:
    paths:
      - "cmpt/*"
  schedule:
    - cron: 0 0 * * 6

jobs:
  build_cmpt:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      shell: bash
      run: |
        ./build.sh cmpt
        docker push moremay/php --all-tags
