name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build_82:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./8.2
        file: ./8.2/Dockerfile
        push: true
        tags: |
          moremay/php:8.2
          moremay/php:8.2-alpine
          
  build_cmpt:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      shell: bash
      run: |
        ./build.sh cmpt && docker push moremay/php --all
