name: "CI: 8.x"

on:
  push:
    paths:
      - "8.4/*"
jobs:
  build_84:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      shell: bash
      run: |
        ./build.sh 8.4 --ali -p
